{"uuid": "63ccc2b5-82ea-4b3b-ac23-32231169f08a", "children": ["450c9641-7ca4-445e-b593-f357f02a2442"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist\nStacktrace:\n\tGetHandleVerifier [0x00007FF6EB13CF45+75717]\n\tGetHandleVerifier [0x00007FF6EB13CFA0+75808]\n\t(No symbol) [0x00007FF6EAF08F9A]\n\t(No symbol) [0x00007FF6EAF4B9D9]\n\t(No symbol) [0x00007FF6EAF46759]\n\t(No symbol) [0x00007FF6EAF41ADD]\n\t(No symbol) [0x00007FF6EAF952D8]\n\t(No symbol) [0x00007FF6EAF948B0]\n\t(No symbol) [0x00007FF6EAF87153]\n\t(No symbol) [0x00007FF6EAF50421]\n\t(No symbol) [0x00007FF6EAF511B3]\n\tGetHandleVerifier [0x00007FF6EB43D71D+3223453]\n\tGetHandleVerifier [0x00007FF6EB437CC2+3200322]\n\tGetHandleVerifier [0x00007FF6EB455AF3+3322739]\n\tGetHandleVerifier [0x00007FF6EB156A1A+180890]\n\tGetHandleVerifier [0x00007FF6EB15E11F+211359]\n\tGetHandleVerifier [0x00007FF6EB145294+109332]\n\tGetHandleVerifier [0x00007FF6EB145442+109762]\n\tGetHandleVerifier [0x00007FF6EB12BA59+4825]\n\tBaseThreadInitThunk [0x00007FF876F5E8D7+23]\n\tRtlUserThreadStart [0x00007FF878ADC5DC+44]\n\n", "trace": "  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\LoadTest\\conftest.py\", line 20, in driver\n    driver = webdriver.Chrome(service=service, options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 67, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 260, in __init__\n    self.start_session(capabilities)\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 448, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\LoadTest\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1747846665667, "stop": 1747846728593}], "start": 1747846665667, "stop": 1747846738802}